# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13dee57b49abe9c16b6e23672b36b30b324469b6a252f3688fe670c8d43fcc6558c08038d6061b39c59c712bcdf6e5d38fc1dab2bf79f60c6032e36bb81fbe9d

test:
  secret_key_base: 08bb3035ee5c50996eb56e2610ff54765555301076236f0d415810e53dee531bea7eb9a3b54276d9fc17b56d6b50a2f74d9e063a54b2723af2267216998b5a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
