# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b53fbec1c43f8e01ae6255dbd3bd210e48e6017cab03f8a6a71d8f54da4015770b6015507ccca0ca72b7d5eccd4d3de0efb35b3e287673a010d62634a719f6d

test:
  secret_key_base: 73ca7699cd744af39f273fd8f88bb8659075f173aa99ba54fc093211185f6a7cac360a454706b16fdc0f5d1eabb6955adb6f9efc96f4115b2758fb4a8ed4f8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
